### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by javiermon** [Nessus85100/tlbb#5]
Hi

Currently there are 2 missing labels in the skin settings, XBMC mode:
- On Home window, after Hide Now Playing Music Info, the text for Show Library Totals (SkinSettings.xml, line 207).
- On Backgrounds, after Disable Fanart in all sections, the text for Hide Background Video (SkinSettings.xml, line 235).

Thanks,

**Comment by Nessus85100** [comment]
Thanks for reporting these. Will fix them in the next update.

Cheers
Nessus

**Comment by Nessus85100** [comment]
9f9c07236718a0c45c7e8adc50613df0e65e62dd
