### ISSUE TITLE
Missing views

### ISSUE THREAD

**Issue by javiermon** [Nessus85100/tlbb#6]
Hi

In the skin settings you can enable additional views, like wall and 3d wall, but once enabled they don't appear when changing a view.

Thanks

**Comment by Nessus85100** [comment]
Crap!. I messed up there after recoding of the dialog. Will fix it in the next update.
Thanks a lot for reporting. I really appreciate it.

Cheers
nessus

**Comment by Nessus85100** [comment]
2c799568a811454cbcab65226ea4bda61ba7789c
